// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGo1l5rRW7CCxPNPqLIqzq-3bTBC6wY8',
    appId: '1:778555287690:web:90c942b058497abb3be573',
    messagingSenderId: '778555287690',
    projectId: 'u-learning-app-d67d7',
    authDomain: 'u-learning-app-d67d7.firebaseapp.com',
    storageBucket: 'u-learning-app-d67d7.appspot.com',
    measurementId: 'G-6B9LE5PVPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU91JkKPjlyh6HJt4eJXUGt5fa8Sxj0_U',
    appId: '1:778555287690:android:1e97a51a11dccb7c3be573',
    messagingSenderId: '778555287690',
    projectId: 'u-learning-app-d67d7',
    storageBucket: 'u-learning-app-d67d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuL-4WeU-n569w6jkjwXOx1sBH8OmHv7A',
    appId: '1:778555287690:ios:df7911e8d9129ff13be573',
    messagingSenderId: '778555287690',
    projectId: 'u-learning-app-d67d7',
    storageBucket: 'u-learning-app-d67d7.appspot.com',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuL-4WeU-n569w6jkjwXOx1sBH8OmHv7A',
    appId: '1:778555287690:ios:48fe8abb33cbcdc33be573',
    messagingSenderId: '778555287690',
    projectId: 'u-learning-app-d67d7',
    storageBucket: 'u-learning-app-d67d7.appspot.com',
    iosBundleId: 'com.example.ulearningApp.RunnerTests',
  );
}
